# fly.toml app configuration file generated for mt-life on 2024-01-10T18:09:28+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mt-life"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[build]

[deploy]
  release_command = "./bin/rails db:prepare"

[env]
  MALLOC_ARENA_MAX = "2"  # メモリ管理の環境変数設定sidekiq用

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false  # スリープなし
  auto_start_machines = true
  min_machines_running = 1  # 常に1台のインスタンスを稼働
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[processes]
  app = "bin/rails server"
  worker = "bundle exec sidekiq"

[[services]]
  processes = ["app", "worker"]
  internal_port = 3000
  protocol = "tcp"
  force_https = true