development:
  adapter: redis
  #secret_key_base: <development_secret_key>
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: MT_Life_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: MT_Life_production