default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: MTLife
  password: 0000
  host: localhost

development:
  <<: *default
  database: MTLife_development

test:
  <<: *default
  database: MTLife_test

production:
  <<: *default
  password: <%= ENV["MTLIFE_DATABASE_PASSWORD"] %>
