:concurrency: 2
:queues:
  - default

:schedule:
  message_job:
    cron: "0 9 * * 1"
    class: "MessageJob"
    queue: default
    description: "毎週月曜日の朝9:00にメッセージを送信"
    tz: "Asia/Tokyo"

  cleanup_job:
    cron: "0 3 * * *"
    class: "CleanupJob"
    queue: default
    description: "毎日3:00に古いファイルを削除"
    tz: "Asia/Tokyo"